### ISSUE TITLE
JSON.parse: unexpected character at line 1 column 1 of the JSON data

### ISSUE THREAD

**Issue by ramnikwebs** [xdan/jodit-connectors#1]
Unable To upload File 
![bug](https://cloud.githubusercontent.com/assets/20019495/16174124/599f9df0-35d3-11e6-8632-0cd786b4f3a3.jpg)

**Comment by xdan** [comment]
Please update connector and Jodit. On the screen Jodit 2. This repository for [Jodit 3](https://github.com/xdan/jodit)

**Comment by mikaaaaay** [comment]
Hi, Im having issues in uploading the file. I have downloaded both Jodit editor latest version as well as the connector. I am new to programming so I am not sure if what I did was right. 
I have created a config.php  because I can't fine one in the files and you have instructed it. 

![image](https://user-images.githubusercontent.com/48289777/53895005-0b324400-406c-11e9-90a7-be02177c8ca2.png)

but it seems its still not working. 
![image](https://user-images.githubusercontent.com/48289777/53894784-b1ca1500-406b-11e9-8a38-980f3714c9f9.png)
